name: flutter_localization_sample
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  get: 3.4.6
  easy_localization: 2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/flags/english_flag.png
    - assets/flags/spanish_flag.png
    - assets/flags/hindi_flag.png
    - assets/flags/indonesian_flag.png
    - assets/flags/japanese_flag.png
    - assets/flags/portuguese_flag.png
    - assets/flags/russian_flag.png
    - assets/flags/spanish_flag.png
    - assets/flags/thai_flag.png
    - assets/flags/turkish_flag.png
    - assets/flags/vietnamese_flag.png

